### ISSUE TITLE
Package.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by d4k0** [schmitzjake/monokai-seti#13]
Since the update to Atom 0.189.0, this message appears:

Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `atom-ternjs` package
```
ThemePackage.getStylesheetsPath (D:\Programme\Dokumente\Atom\resources\app\src\package.js:448:9)
<unknown> (D:\Programme\Dokumente\Atom\resources\app\src\theme-manager.js:492:35)
```

**Comment by schmitzjake** [comment]
This is a problem with the atom-terns package, file this issue under that packages repo

**Comment by d4k0** [comment]
Well, in fact this seems to affect many packages as Atom now expects a folder called "styles" instead of "stylesheets" (the atom-terns package was also affected, I reported it to the developer and he fixed it yesterday). This is how it looks like with a new profile and only monokai-seti installed:

![Monokai-Seti with fresh profile](https://i.imgur.com/U7ZUL1t.png)

The fix seems to pretty easy: [One has to simply rename the directory.](https://github.com/tststs/atom-ternjs/commit/c61f2e02d3ec427b47cc6982fb317d7024570f9d)

**Comment by schmitzjake** [comment]
I'll try and get to this tonight. If not the pull request should be super easy if you want to fork and make a pull

**Comment by d4k0** [comment]
[Done.](https://github.com/schmitzjake/monokai-seti/pull/14) I tested it and it seems to work (the depracation warning doesn't appear anymore).

**Comment by schmitzjake** [comment]
Awesome! I'll get on publishing it right now
