### ISSUE TITLE
Atom Shows Warnings Regarding Switch to Shadow DOM

### ISSUE THREAD

**Issue by killercup** [schmitzjake/monokai-seti#2]
This is the warning in Atom's console, verbatim:

- - -

Upgraded the following syntax theme selectors in `/Users/pascal/.atom/packages/seti-monokai/index.less` for shadow DOM compatibility:

`.editor-colors` => `:host`
`.editor .invisible-character` => `:host .invisible-character`
`.editor .indent-guide` => `:host .indent-guide`
`.editor .wrap-guide` => `:host .wrap-guide`
`.editor .gutter` => `:host .gutter`
`.editor .gutter .cursor-line` => `:host .gutter .cursor-line`
`.editor .line-number.cursor-line-no-selection` => `:host .line-number.cursor-line-no-selection`
`.editor .invisible` => `:host .invisible`
`.editor .cursor` => `:host .cursor`
`.editor .selection .region` => `:host .selection .region`
`.editor .search-results .marker .region` => `:host .search-results .marker .region`
`.editor .search-results .marker.current-result .region` => `:host .search-results .marker.current-result .region`
`.editor .comment` => `:host .comment`
`.editor .string` => `:host .string`
`.editor .constant.numeric` => `:host .constant.numeric`
`.editor .constant.language` => `:host .constant.language`
`.editor .constant.character, .editor .constant.other` => `:host .constant.character, :host .constant.other`
`.editor .keyword` => `:host .keyword`
`.editor .storage` => `:host .storage`
`.editor .storage.type` => `:host .storage.type`
`.editor .entity.name.class` => `:host .entity.name.class`
`.editor .entity.other.inherited-class` => `:host .entity.other.inherited-class`
`.editor .entity.name.function` => `:host .entity.name.function`
`.editor .entity.name.instance` => `:host .entity.name.instance`
`.editor .variable.parameter` => `:host .variable.parameter`
`.editor .entity.name.tag` => `:host .entity.name.tag`
`.editor .entity.other.attribute-name` => `:host .entity.other.attribute-name`
`.editor .support.function` => `:host .support.function`
`.editor .support.constant` => `:host .support.constant`
`.editor .support.type, .editor .support.class` => `:host .support.type, :host .support.class`
`.editor .invalid` => `:host .invalid`
`.editor .invalid.deprecated` => `:host .invalid.deprecated`
`.editor .class.jade` => `:host .class.jade`
`.editor .gfm .markup.heading` => `:host .gfm .markup.heading`
`.editor .gfm .markup.underline` => `:host .gfm .markup.underline`
`.editor .gfm .bold` => `:host .gfm .bold`
`.editor .gfm .italic` => `:host .gfm .italic`
`.editor .gfm .raw` => `:host .gfm .raw`
`.editor .gfm .variable.list` => `:host .gfm .variable.list`
`.editor .gfm .link` => `:host .gfm .link`
`.editor .gfm .link .entity` => `:host .gfm .link .entity`

See the upgrade guide for information on removing this warning.

**Comment by schmitzjake** [comment]
Will make the change. Should be a quick fix

**Comment by schmitzjake** [comment]
resolved
